CREATE TABLE users (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    mobile VARCHAR(10) NOT NULL,
    age INT(11) NOT NULL,
    voter_id VARCHAR(10) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);
